### ISSUE TITLE
OAuth.jsx is creating an error

### ISSUE THREAD

**Issue by Yashharamkar** [sahandghavidel/mern-blog#1]
while I am using authentication for gmail through firebase it is creating me an error and I am unable to sign it out with gmail...
It is showing   OAuth.jsx:18 
        
        
       POST http://localhost:5173/api/auth/google 500 (Internal Server Error)
handleGoogleClick @ OAuth.jsx:18
await in handleGoogleClick (async)
callCallback2 @ chunk-T7VP4UGM.js?v=700d354d:3674
invokeGuardedCallbackDev @ chunk-T7VP4UGM.js?v=700d354d:3699
invokeGuardedCallback @ chunk-T7VP4UGM.js?v=700d354d:3733
invokeGuardedCallbackAndCatchFirstError @ chunk-T7VP4UGM.js?v=700d354d:3736
executeDispatch @ chunk-T7VP4UGM.js?v=700d354d:7016
processDispatchQueueItemsInOrder @ chunk-T7VP4UGM.js?v=700d354d:7036
processDispatchQueue @ chunk-T7VP4UGM.js?v=700d354d:7045
dispatchEventsForPlugins @ chunk-T7VP4UGM.js?v=700d354d:7053
(anonymous) @ chunk-T7VP4UGM.js?v=700d354d:7177
batchedUpdates$1 @ chunk-T7VP4UGM.js?v=700d354d:18909
batchedUpdates @ chunk-T7VP4UGM.js?v=700d354d:3579
dispatchEventForPluginEventSystem @ chunk-T7VP4UGM.js?v=700d354d:7176
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ chunk-T7VP4UGM.js?v=700d354d:5478
dispatchEvent @ chunk-T7VP4UGM.js?v=700d354d:5472
dispatchDiscreteEvent @ chunk-T7VP4UGM.js?v=700d354d:5449
Show 15 more frames
Show less
OAuth.jsx:33 SyntaxError: Unexpected end of JSON input in the browser
kindly help me to solve this issur

**Comment by vaibhavbaneshi** [comment]
Hello fellow coder, I encountered the same error in my code. In my code, it occurred when I was creating a new user using OAuth.
I think it's because the await functionality is not being able to execute as intended. To resolve this error I just added a
"console.log(res.json(newUser))" after generating tokens and the error was removed. I hope it works for you as well.

My GitHub Repository: https://github.com/vaibhavbaneshi/MERN-BLOG
My code:

 const generatedPassword = Math.random().toString(36).slice(-8) + Math.random().toString(36).slice(-8)
        const hashedPassword = bcryptjs.hashSync(generatedPassword, 10)

        const newUser = await User.create({
            username: name?.toLowerCase().split(' ').join('') + Math.random().toString(9).slice(-4),
            email,
            password: hashedPassword,
            profilePicture: googlePhotoURL
        })

        const {accessToken, refreshToken} = await generateAccessandRefreshToken(newUser._id) // used a custom method to 
                                                                                                                                                           generate tokens

        const loggedInUser = await User.findById(newUser._id).select("-password -refreshToken")

        console.log(res.json(loggedInUser));
